# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 11:25
from __future__ import unicode_literals

import core.colors
import core.tools.name_generator
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_auto_20170809_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=100)),
                ('color', models.CharField(default=core.colors.random_color, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_users', models.ManyToManyField(through='core.Availability', to='core.ClientUser')),
            ],
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rollout_strategy', models.CharField(choices=[('recall_feature', 'Recall Feature'), ('pause_rollout', 'Pause Roll Out'), ('defined_by_releases', 'As defined by Releases'), ('enable_globally', 'Enable Globally')], default='defined_by_releases', max_length=50)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.App')),
            ],
            options={
                'verbose_name_plural': 'Functionalities',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=core.tools.name_generator.generate_name, max_length=100)),
                ('start_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('end_at', models.DateTimeField(default=datetime.datetime(5000, 1, 1, 0, 0))),
                ('max_enabled_users', models.IntegerField(default=0)),
                ('functionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Functionality')),
            ],
        ),
        migrations.AddField(
            model_name='flavor',
            name='functionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Functionality'),
        ),
        migrations.AddField(
            model_name='availability',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Flavor'),
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClientUser'),
        ),
    ]
