# Generated by Django 2.1 on 2018-08-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Release", new_name="RolloutStrategy",),
    ]
