# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='functionality',
            options={'verbose_name_plural': 'Functionalities'},
        ),
        migrations.AddField(
            model_name='functionality',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
