# Generated by Django 2.1.7 on 2019-11-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0001_initial'),
        ('core', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolloutstrategy',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.Tag'),
        ),
        migrations.AddField(
            model_name='functionality',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.App'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='client_users',
            field=models.ManyToManyField(through='core.Availability', to='core.ClientUser'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='functionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Functionality'),
        ),
        migrations.AddField(
            model_name='availability',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Flavor'),
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClientUser'),
        ),
        migrations.AddField(
            model_name='app',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='rolloutstrategy',
            unique_together={('tag', 'functionality')},
        ),
    ]
