# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 11, 21, 7, 514358, tzinfo=utc)),
        ),
    ]
