# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170812_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['start_at']},
        ),
        migrations.AlterField(
            model_name='functionality',
            name='rollout_strategy',
            field=models.CharField(choices=[('recall', 'Recall'), ('pause_rollout', 'Roll Out Paused'), ('defined_by_releases', 'Release-Driven'), ('enable_globally', 'Enabled Globally')], default='defined_by_releases', max_length=50),
        ),
        migrations.AlterField(
            model_name='release',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
