# Generated by Django 2.1 on 2018-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20180816_1218"),
    ]

    operations = [
        migrations.RemoveField(model_name="functionality", name="rollout_strategy",),
        migrations.AddField(
            model_name="rolloutstrategy",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("recall", "Recall"),
                    ("pause_rollout", "Roll Out Paused"),
                    ("defined_by_releases", "Release-Driven"),
                    ("enable_globally", "Enabled Globally"),
                ],
                default="defined_by_releases",
                max_length=50,
            ),
        ),
    ]
