# Generated by Django 2.1 on 2018-08-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tagging", "0003_auto_20180809_1305"),
        ("core", "0004_auto_20180817_0937"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="rolloutstrategy", unique_together={("tag", "functionality")},),
    ]
