# Generated by Django 2.1.7 on 2019-11-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rolloutstrategy_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolloutstrategy',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.Tag'),
        ),
    ]
