# Generated by Django 2.2.7 on 2020-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191124_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
