# Generated by Django 2.1.7 on 2019-11-28 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Organization')),
                ('users', models.ManyToManyField(to='core.ClientUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'organization')},
        ),
    ]
