# Generated by Django 2.0.6 on 2018-08-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField()),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_management.Organization")),
                ("user", models.ManyToManyField(to="core.ClientUser")),
            ],
        ),
    ]
